### ISSUE TITLE
Allow to select order column

### ISSUE THREAD

**Issue by ariera** [aaparmeggiani/pg_tail#3]
Hi, first of all great tool, very useful :)

I have a feature request. It looks like the way to order the table is by `id`, which is fine if ids are integers, but in my particular case i'm using UUIDs, and I would need to order by `created_at`.

I would be nice to be able to select with an option based on which column it should be sorted, something like:

```
  -o, --order=COL          orders in descending order by this column
```

**Comment by ariera** [comment]
Alright, I just realised this is already possible. `pg_tail` will order by the first column selected in the `-c` option :)

**Comment by aaparmeggiani** [comment]
Hey Alejandro, thanks for your feedback!

It's not clear in the help, but the 1st column (uKEY) is used to sort the table in a guaranteed ascending order so that new insertions will always be caught  between pollings. If your column doesn't support a natural order (sequence, timestamp) you might miss insertions.

**Comment by dturon** [comment]
Hi, looks very nice.

You can simply improve your tool for multicolumn primary keys for example table (ts timestamptz, name text, data text) PRIMARY KEY(ts,name)
with -c name,ts,data just change where and order by:
WHERE (ts, name, data)>=($last_ts, $last_name, $last_data) ORDER BY ts, name, data LIMIT $x
like described here http://use-the-index-luke.com/sql/partial-results/fetch-next-page 
Its only idea i do not need this now, but can be usefull for someone;)

David

**Comment by dturon** [comment]
Of course help only for sampled data with same timestamps.

**Comment by aaparmeggiani** [comment]
Thank you, David!

The only way to guarantee it is through a sequence (ordered, unique). We could use all columns in the ORDER BY and still miss or show inserts in the wrong order.  

In your example, if pg_tail happens to pool in between INSERT ('2016-09-06 00:00:00', 'Bob')  and INSERT ('2016-09-06 00:00:00', 'Alice'), the second would not be shown.  Even in the same pool, they wouldn't come in the same order as inserted.

As far as I know, Postgresql doesn't keep an internal sequence (ctid can be ovewriten)  and using LISTEN/NOTIFY would require triggers (privileges dependent)

**Comment by dturon** [comment]
Yes, sorry i did not realize...nevermind:)

**Comment by aaparmeggiani** [comment]
Hey, no worries David, I didn't realize too .. until you commented  ;)   Thanks again!

**Comment by aaparmeggiani** [comment]
Probably worth adding some lines in the readme ..
