### ISSUE TITLE
Can't build on Ubuntu

### ISSUE THREAD

**Issue by ruipacheco** [aaparmeggiani/pg_tail#4]
vagrant@precise64:~/pg_tail$ make
cc -Wall -O2 -I`pg_config --includedir` -L`pg_config --libdir` -lpq -o pg_tail pg_tail.c
/tmp/cckvqetS.o: In function `exit_nicely':
pg_tail.c:(.text+0xa): undefined reference to `PQfinish'
/tmp/cckvqetS.o: In function `main':
pg_tail.c:(.text.startup+0x2cf): undefined reference to `PQsetdbLogin'
pg_tail.c:(.text.startup+0x2dc): undefined reference to `PQstatus'
pg_tail.c:(.text.startup+0x35b): undefined reference to `PQexec'
pg_tail.c:(.text.startup+0x366): undefined reference to `PQresultStatus'
pg_tail.c:(.text.startup+0x377): undefined reference to `PQntuples'
pg_tail.c:(.text.startup+0x383): undefined reference to `PQnfields'
pg_tail.c:(.text.startup+0x3cf): undefined reference to `PQgetvalue'
pg_tail.c:(.text.startup+0x3f9): undefined reference to `PQfname'
pg_tail.c:(.text.startup+0x416): undefined reference to `PQfname'
pg_tail.c:(.text.startup+0x43b): undefined reference to `PQgetvalue'
pg_tail.c:(.text.startup+0x4b9): undefined reference to `PQgetvalue'
pg_tail.c:(.text.startup+0x512): undefined reference to `PQgetvalue'
pg_tail.c:(.text.startup+0x527): undefined reference to `PQclear'
pg_tail.c:(.text.startup+0x56a): undefined reference to `PQerrorMessage'
pg_tail.c:(.text.startup+0x581): undefined reference to `PQclear'
pg_tail.c:(.text.startup+0x5b6): undefined reference to `PQfname'
pg_tail.c:(.text.startup+0x5f2): undefined reference to `PQerrorMessage'
collect2: ld returned 1 exit status
make: *** [pg_tail] Error 1
vagrant@precise64:~/pg_tail$

**Comment by aaparmeggiani** [comment]
I could reproduce the error from ubuntu:latest  (Docker)  + needed packages installed

Closest I've got was https://github.com/will/crystal-pg/issues/13   ...

**Comment by aaparmeggiani** [comment]
Sorted!  

http://stackoverflow.com/questions/27144588/undefined-reference-to-pqfinish-even-though-libraries-etc-are-included   (aka, the order of the args changes the result :^/

Tested on ubuntu:latest; Dockerfile as follows:


```
from ubuntu:latest

 RUN apt-get update
 RUN apt-get install -y \
 		git \
 		make \
 		gcc \
 		postgresql-server-dev-all

RUN git clone https://github.com/aaparmeggiani/pg_tail.git

WORKDIR pg_tail
RUN make

```
