### ISSUE TITLE
pg_tail to write to files

### ISSUE THREAD

**Issue by nazeemmohammed** [aaparmeggiani/pg_tail#5]
Hello, I was using this utility on a postgresql rds instance and writing it to a file rather displaying the output on the stdout. 

pg_tail -h xxxx -d xxxx -p xxx > /tmp/pgtail.out &

When its run like this, the data is not getting written. Probably due to the c printf function waiting for the buffer to fill up. I made below change and then it was able to write the output as soon as the data was flowing into the table.

 ```
  /* header if 1st lap */
    if(!current_key && num_rows > 0) {
      for(i = 0; i < num_fields; i++)
        printf("%-*s%s", col_length[i], PQfname(res, i), op_separator);
      printf("\n");
      fflush(stdout); -- new code
    }
    /* rows */
    for (i = 0; i < num_rows; i++) {
      for (j = 0; j < num_fields; j++)
        printf("%-*s%s", (op_align * col_length[j]), PQgetvalue(res, i, j), op_separator);
      printf("\n");
      fflush(stdout);  -- new code
    }
```

Please check and advice.

**Comment by aaparmeggiani** [comment]
Great catch, Nazeem ..  committed with your credits.

Thanks very much!

**Comment by nazeemmohammed** [comment]
Thanks a lot Andre.
