### ISSUE TITLE
Rather monitoring the output of a query

### ISSUE THREAD

**Issue by fscemama** [aaparmeggiani/pg_tail#7]
Hi !
Thank you very much for the nice piece of code. It helps.
May I suggest that the parameters get a query, rather than a table and column names ? Then, we could get the output of junctions.
Thanks !

**Comment by aaparmeggiani** [comment]
Hi @fscemama, that's a great idea, thank you!  Thinking a bit about it, it just occurred to me that the [watch](https://en.wikipedia.org/wiki/Watch_(Unix)) command would be more flexible for the job (?) (.. to the point of making pg_tail useless :-)
```
watch -n 5 'echo "select id, name from users order by id desc limit 10" | psql -e "postgres://user:pass@host/database"'
```
*"Those who don't understand Unix are condemned to reinvent it, poorly."* **– Henry Spencer**
