### ISSUE TITLE
Respect PGPASSWORD env variable

### ISSUE THREAD

**Issue by aswinkarthik** [aaparmeggiani/pg_tail#8]
PGPASSWORD is respected by the psql CLI and does not prompt if given

**Comment by aaparmeggiani** [comment]
Fair point, @aswinkarthik.   Actually,  looking at the [env vars](https://www.postgresql.org/docs/12/libpq-envars.html) page,  some of those would be nice to have too, making it easier to config for container/cloud usage. Queued for when time allows, or PR equally welcome.
Thank you!

**Comment by aaparmeggiani** [comment]
done!
