### ISSUE TITLE
Cannot build pg_tail on Alma Linux

### ISSUE THREAD

**Issue by pierreforstmann** [aaparmeggiani/pg_tail#9]
Hello,

I cannot build pg_tail on Alma Linux 8.5. 
I have tried with PG 13.6 and PG 14.2. I'm using pgenv to build PG from source code  : in general I have no issue building PG source code or building my extensions.

I have following issues:
```
gcc -Wall -O2 -I/home/pierre/.pgenv/pgsql-13.6/include  -L/home/pierre/.pgenv/pgsql-13.6/lib -o pg_tail pg_tail.c -lpq
pg_tail.c: In function ‘main’:
pg_tail.c:158:17: warning: implicit declaration of function ‘memset_s’; did you mean ‘memset’? [-Wimplicit-function-declaration]
   if(password){ memset_s(password, strlen(password), 0,  strlen(password)); }
                 ^~~~~~~~
                 memset
/tmp/ccDhZhpB.o: In function `main':
pg_tail.c:(.text.startup+0x3ec): undefined reference to `memset_s'
collect2: error: ld returned 1 exit status
make: *** [Makefile:19: pg_tail] Error 1
```
I understand that memset_s is not available with GNU libc: am I correct ?
Does this mean that pg_tail only works on FreeBSD and MacOS ?

**Comment by aaparmeggiani** [comment]
Hi, 

Looks like the  `_s` functions are optional and not implemented by gcc.  Changed to `memset`.
Thanks for reporting!
